run:
  go: 1.18.3
  build-tags:
    - unit
    - integration
    - racy
    - long
linters-settings:
  dupl:
    threshold: 100
  forbidigo:
    # Forbid the following identifiers
    forbid:
      #- fmt.Errorf # consider errors.Errorf in github.com/pkg/errors
      - fmt.Print.* # too much log noise
      - log.Print.*
  gocognit:
    min-complexity: 8
  funlen:
    lines: 120
    statements: 50
  nestif:
    min-complexity: 8
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: go.eloylp.dev/goomerang
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - nestif
  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gochecknoinits
        - gosec
        - bodyclose
        - scopelint
        - errcheck
        - dupl
        - forbidigo
        - lll
    - path: cmd
      linters:
        - gomnd
        - gochecknoinits
        - gosec
        - bodyclose
        - errcheck
        - dupl
        - forbidigo
        - gocritic
        - goimports
        - goconst
