global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'server'
    static_configs:
      - targets: [ 'server:9971' ]

  - job_name: 'client'
    static_configs:
      - targets: [ 'client:9971' ]

  - job_name: 'client2'
    static_configs:
      - targets: [ 'client2:9971' ]