{
 "title": "Go runtime",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": { "query": "label_values(go_info, app)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_info{app=\"$app\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go version",
   "type": "stat",
   "description": "**go_info** – Provides information about the runtime, like version. Its a gauge.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_info{app=\"$app\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "CPU seconds total",
   "type": "graph",
   "description": "**process_cpu_seconds_total** Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"$app\",kubernetes_pod_name=~\"$instance\"}[5m])",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Open FDs VS Limit",
   "type": "graph",
   "description": "**process_open_fds** Number of open file descriptors.\n\n**process_max_fds** Maximum number of open file descriptors.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app=\"$app\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "process_max_fds{app=\"$app\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory virtual",
   "type": "graph",
   "description": "**process_virtual_memory_bytes**  Virtual memory size in bytes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"$app\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "description": "**process_resident_memory_bytes** Resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"$app\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "description": "**go_threads** – Number of OS threads created.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Goroutines count",
   "type": "graph",
   "description": "**go_goroutines** - Number of goroutines that currently exist.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last GC time",
     "type": "stat",
     "description": "**go_memstats_last_gc_time_seconds** – Number of seconds since 1970 of last garbage collection.",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{app=\"$app\", kubernetes_pod_name=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Next GC heap target",
     "type": "graph",
     "description": "**go_memstats_next_gc_bytes** – Number of heap bytes when next garbage collection will take place.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "GC pauses (quantiles) ",
     "type": "graph",
     "description": "**go_gc_duration_seconds** – A summary of the pause duration of garbage collection cycles.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "quantile - {{quantile}}"
      }
     ]
    },
    {
     "title": "CPU fraction",
     "type": "graph",
     "description": "**go_memstats_last_gc_cpu_fraction** – The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_memstats_last_gc_cpu_fraction{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "quantile - {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory distribution",
     "type": "graph",
     "description": "**go_memstats_sys_bytes** - Number of heap bytes obtained from system. It sums all the sys metrics:\n\n**go_memstats_heap_sys_bytes** – Number of heap bytes obtained from system.\n\n**go_memstats_stack_sys_bytes** – Number of bytes obtained from system for stack allocator.\n\n**go_memstats_mspan_sys_bytes** – Number of bytes used for mspan structures obtained from system.\n\n**go_memstats_mcache_sys_bytes** – Number of bytes used for mcache structures obtained from system.\n\n**go_memstats_buck_hash_sys_bytes** – Number of bytes used by the profiling bucket hash table.\n\n**go_memstats_gc_sys_bytes** – Number of bytes used for garbage collection system metadata.\n\n**go_memstats_other_sys_bytes** Number of bytes used for other system allocations.",
     "gridPos": { "h": 23, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "total from OS "
      },
      {
       "expr": "go_memstats_heap_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "heap"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "stack"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "spans"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "cache"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "ProfBuckhash"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "GCMeta"
      },
      {
       "expr": "go_memstats_other_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Allocated bytes at heap in use",
     "type": "graph",
     "description": "**go_memstats_alloc_bytes** - Number of bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Heap live objects count",
     "type": "graph",
     "description": "**go_memstats_heap_objects** – Number of allocated objects.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Allocations per second",
     "type": "graph",
     "description": "**go_memstats_mallocs_total** – Total number of mallocs.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{app=\"$app\", kubernetes_pod_name=~\"$instance\"}[2m])",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Lookups/dereferences per second",
     "type": "graph",
     "description": "**go_memstats_lookups_total** – Total number of pointer lookups.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{app=\"$app\", kubernetes_pod_name=~\"$instance\"}[2m])",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Memory frees per second",
     "type": "graph",
     "description": "**go_memstats_frees_total** – Total number of frees.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{app=\"$app\", kubernetes_pod_name=~\"$instance\"}[2m])",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Allocated bytes total (even if freed) per second",
     "type": "graph",
     "description": "**go_memstats_alloc_bytes_total** - Total number of bytes allocated, even if freed.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{app=\"$app\", kubernetes_pod_name=~\"$instance\"}[5m])",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory in detail (HEAP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currrent bytes INUSE spans",
     "type": "graph",
     "description": "**go_memstats_heap_inuse_bytes** – Number of heap bytes that are in use.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Currrent bytes in IDLE spans",
     "type": "graph",
     "description": "**go_memstats_heap_idle_bytes** – Number of heap bytes waiting to be used.",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Memory allocated but not used",
     "type": "graph",
     "description": "**go_memstats_heap_inuse_bytes** minus **go_memstats_heap_alloc_bytes** shows how many bytes of memory has been allocated for the heap, but not currently used.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"} - go_memstats_heap_alloc_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Memory that could be returned to OS",
     "type": "graph",
     "description": "**go_memstats_heap_idle_bytes** minus **go_memstats_heap_released_bytes** this is memory that the runtime retains in order to not require more from the OS , so avoid such costly operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"} - go_memstats_heap_released_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Returned bytes of IDLE spans to the OS",
     "type": "graph",
     "description": "**go_memstats_heap_released_bytes** – Number of heap bytes released to OS.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory in detail (STACK)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current in use bytes (stack spans)",
     "type": "graph",
     "description": "**go_memstats_stack_inuse_bytes** – Number of bytes in use by the stack allocator.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Stack memory obtained from OS",
     "type": "graph",
     "description": "**go_memstats_stack_inuse_bytes** – Number of bytes obtained from system for stack allocator.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory detail (RUNTIME)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "From OS mscache bytes",
     "type": "graph",
     "description": "**go_memstats_mcache_sys_bytes** – Number of bytes used for mcache structures obtained from system.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "From OS mspan bytes",
     "type": "graph",
     "description": "**go_memstats_mspan_sys_bytes** – Number of bytes used for mspan structures obtained from system.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "In use mspan bytes",
     "type": "graph",
     "description": "**go_memstats_mspan_inuse_bytes** – Number of bytes in use by mspan structures.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "mspan cache bytes",
     "type": "graph",
     "description": "**go_memstats_mcache_inuse_bytes** – Number of bytes in use by mcache structures.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Current GC metadata bytes",
     "type": "graph",
     "description": "**go_memstats_gc_sys_bytes** – Number of bytes used for garbage collection system metadata.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Current bucket hash tables bytes",
     "type": "graph",
     "description": "**go_memstats_buck_hash_sys_bytes** – Number of bytes used by the profiling bucket hash table.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{app=\"$app\", kubernetes_pod_name=~\"$instance\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  }
 ]
}