{
 "title": "Goomerang",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "servers", "label": "Servers", "query": { "query": "goomerang_server_status" } },
   { "name": "clients", "label": "Clients", "query": { "query": "goomerang_client_status" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server errors",
   "type": "stat",
   "description": "The error rate of the server in the selected time range.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(goomerang_server_errors_total{instance=~\"$servers\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Server status",
   "type": "state-timeline",
   "description": "The current status of the servers. BEWARE this is a gauge metric. That means the accuracy will depend on your scrape interval, so if the status change is very quick, no changes will appear on this panel.",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "goomerang_server_status{instance=~\"$servers\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Max concurrency",
   "type": "stat",
   "description": "The maximum allowed concurrency for the server via configuration. Refers to WithMaxConcurrency() option.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(goomerang_server_config_max_concurrency{instance=~\"$servers\"}) / count(goomerang_server_config_max_concurrency{instance=~\"$servers\"})"
    }
   ]
  },
  {
   "title": "Server concurrency (avg of all servers)",
   "type": "stat",
   "description": "The current number of handlers in execution.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(goomerang_server_concurrent_workers{instance=~\"$servers\"}) / count(goomerang_server_concurrent_workers{instance=~\"$servers\"})"
    }
   ]
  },
  {
   "title": "Server message received rate (rps)",
   "type": "stat",
   "description": "The rate of messages received by the server.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(goomerang_server_message_received_inflight_duration_seconds_count{instance=~\"$servers\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Server message sent rate (rps)",
   "type": "stat",
   "description": "The server message sent ratemin RPS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(goomerang_server_message_sent_size_bytes_count{instance=~\"$servers\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Client errors",
   "type": "stat",
   "description": "The error rate of the clients in the selected time range.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(goomerang_client_errors_total{instance=~\"$clients\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Client status",
   "type": "state-timeline",
   "description": "The current status of the clients.BEWARE this is a gauge metric. That means the accuracy will depend on your scrape interval, so if the status change is very quick, no changes will appear on this panel.",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "goomerang_client_status{instance=~\"$clients\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Max concurrency (avg of all clients)",
   "type": "stat",
   "description": "The maximum allowed concurrency for the client via configuration. Refers to WithMaxConcurrency() option.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(goomerang_client_config_max_concurrency{instance=~\"$clients\"}) / count(goomerang_client_config_max_concurrency{instance=~\"$clients\"})"
    }
   ]
  },
  {
   "title": "Client concurrency (avg of all clients)",
   "type": "stat",
   "description": "The current number of handlers in execution.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(goomerang_client_concurrent_workers{instance=~\"$clients\"}) / count(goomerang_client_concurrent_workers{instance=~\"$clients\"})"
    }
   ]
  },
  {
   "title": "Client message received rate (rps)",
   "type": "stat",
   "description": "The client message receive rate RPS.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(goomerang_client_message_received_inflight_duration_seconds_count{instance=~\"$clients\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Client message sent rate (rps)",
   "type": "stat",
   "description": "The client message sent ratemin RQPS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(goomerang_client_message_sent_duration_seconds_count{instance=~\"$clients\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Server message sent sizes",
   "type": "bargauge",
   "description": "The sent message sizes distribution per message kind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (kind)(rate(goomerang_server_message_sent_size_bytes_sum{instance=~\"$servers\"}[$__rate_interval])) /\nsum by (kind)(rate(goomerang_server_message_sent_size_bytes_count{instance=~\"$servers\"}[$__rate_interval]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Client message sent sizes",
   "type": "bargauge",
   "description": "The sent message sizes distribution per message kind.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (kind)(rate(goomerang_client_message_sent_size_bytes_sum{instance=~\"$clients\"}[$__rate_interval])) /\nsum by (kind)(rate(goomerang_client_message_sent_size_bytes_count{instance=~\"$clients\"}[$__rate_interval]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server message received in-flight time",
     "type": "timeseries",
     "description": "The time a message spent in the wire since sent from the client to the server. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_received_inflight_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_received_inflight_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le)(rate(goomerang_server_message_received_inflight_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message processing time",
     "type": "timeseries",
     "description": "The time a server message handler spends processing a message.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_processing_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_processing_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_server_message_processing_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message received size",
     "type": "timeseries",
     "description": "The size of messages that the server receives.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_received_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_received_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_server_message_received_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Broadcast operation time",
     "type": "timeseries",
     "description": "The time a message broadcast leaves the server. Measures the time of the whole operation, which can involve multiple messages. WARNING, this only indicates the time server flushes data to the buffer. High times could indicate contention due to the client not acking messages.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_broadcast_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_broadcast_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_server_message_broadcast_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message sent time",
     "type": "timeseries",
     "description": "The time a message leaves the server. WARNING, this only indicates the time server flushes data to the buffer. High times could indicate contention due to the client not acking messages.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_server_message_sent_duration_seconds_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message sent size",
     "type": "timeseries",
     "description": "The size of messages that leaves the server.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_server_message_sent_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_server_message_sent_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_server_message_sent_size_bytes_bucket{instance=~\"$servers\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message received in-flight time",
     "type": "timeseries",
     "description": "The time a message spent in the wire since sent from the server to the client. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_received_inflight_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_received_inflight_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le)(rate(goomerang_client_message_received_inflight_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message processing time",
     "type": "timeseries",
     "description": "The time a client message handler spends processing a message.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_processing_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_processing_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_client_message_processing_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message received size",
     "type": "timeseries",
     "description": "The size of messages that the client receives.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_received_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_received_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_client_message_received_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message sent size",
     "type": "timeseries",
     "description": "The size of messages that leaves the client.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_sent_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_sent_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_client_message_sent_size_bytes_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message sent time",
     "type": "timeseries",
     "description": "The time a message leaves the client. WARNING, this only indicates the time server flushes data to the buffer. High times could indicate contention due to the servre not acking messages.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_sent_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_sent_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_client_message_sent_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Message sync roundtrip time",
     "type": "timeseries",
     "description": "The time between a synchronous message is sent to the server and the arrive of its respective reply.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(goomerang_client_message_sent_sync_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(goomerang_client_message_sent_sync_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(goomerang_client_message_sent_sync_duration_seconds_bucket{instance=~\"$clients\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  }
 ]
}